apiVersion: v1
kind: PersistentVolume
metadata:
  ... 
  name: a-pv 
spec: 
  ...
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node
        operator: In
        values: 
        - node-1 