apiVersion: v1 
kind: Pod
metadata: 
  name: a-pod
spec: 
  containers:
  - name: app
    image: nginx 
resources: 
  requests: 
    memory: "100M"
    cpu: "200m"
  limits: 
    memory: "150M"
    cpu: "500m"