apiVersion: v1
kind: Pod
metadata:
  name: my-pod 
spec:
  containers:
  - image: nginx 
    name: container
    volumeMounts:
    - mountPath: /home/
      name: my-vol 
  volumes:
  - name: my-vol 
    persistentVolumeClaim:
      claimName: rok-pvc 