apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rok-pvc 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rok
  volumeMode: Filesystem